### ISSUE TITLE
Create evaluation form for hack night event

### ISSUE THREAD

**Issue by Joshuarainwater** [KCWeb3/Organizational-Growth#1]

**Comment by Joshuarainwater** [comment]
@DCLAW I'll message you to get your input on this

**Comment by DCLAW** [comment]
I don't remember the specific topics that we discussed last time, but here are some things that come to mind for me right now...certainly open to other feedback/ideas...

- Going into the event, did you feel like you had a good/clear idea of what the event would cover and accomplish?
- After attending, do you feel like the event met your expectations?
- If we missed any of your expectations, can you share those with us?
- What can we do better next time? (There's always something we can do better...we want your honest feedback)
- Do you have any ideas for topics to cover in our next event?
